version: 0.0
os: linux
files:
  - source: target/one-app-0.0.1-SNAPSHOT.jar
    #  上传文件夹位置
    destination: /home/ubuntu/oneapp

hooks:
  ApplicationStop:
    - location: scripts/stop_server
      #    超时时间
      timeout: 300
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
